site_name: 繁星若尘的Notebook
repo_url: 'https://github.com/zjuer-dm/Notebook.git'
repo_name: 'GitHub'

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/zjuer-dm'
  alternate: # change the language, the link should point to different directories
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /
      lang: zh
  
  analytics:
    provider: google
    property: G-2M5EHKC0BH

extra_javascript:
  - js/katex.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js
  - assets/js/katex-render.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; ZJU_RCS

theme:
  name: 'material'
  
  font:
    text: LXGW WenKai Screen
    code: Monaspace Krypton
  features:
    - navigation.tabs  # 启用上边栏导航
    - navigation.top  # 启用上边栏导航
    - navigation.instant  # 提升导航速度
    - navigation.indexes  # 启用索引导航
    - content.tabs.link  # 启用内容链接选项卡
    - palette.toggle  # 启用夜间模式切换
    - header.autohide  # 启用自动隐藏头部
    - navigation.sections  # 启用导航部分
    - navigation.expand  # 启用导航展开
  palette:
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt # the github cat icon in the topright
    logo: material/book # the cat icon in the topleft
    annotation: material/star-four-points-circle


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  
     
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: 'index.md'
  
  - 机器人相关:
      - 机器人学: 'robot/Robotics.md'
      - ros相关: 'robot/ros.md'
      - Transformer : 'control/transformer.md'
      - Yolov : 'robot/yolov.md'
      - 机器人零散知识: 'robot/others_robot.md'
      - isaac_sim: 'robot/isaac_sim.md'
      - LI-GS_and_RISED: 'robot/LI-GS_and_RISED.md'
  - 控制学科:
      - 机器视觉 : 'control/machine_vision.md'
      - 最优化理论: 'control/Computational_Methods_For_Optimization.md'
      - 智能控制 : 'control/Intelligent_control.md'
      - 控制理论: 'control/control_system.md'
      - 信号与系统: 'control/信号与系统.md'
  - 人工智能:
      - Attention机制: 'machine_learning/Attention.md'
      - Finetune: 'machine_learning/fine_tune.md'
      - Tokenization: 'machine_learning/Tokenization.md'
      - Encoder-Decoder: 'machine_learning/Encoder_Decoder.md'
      - 优化器: 'machine_learning/optimizer.md'
  - 计算机: 
      - 目录: 'computer/computer.md'
      - 算法学习: 'computer/algorithm.md'
      - 计算机组成: 'control/computer_system.md'
      - 计算机网络: 'computer/computer_web.md'
      - 操作系统: 'computer/os.md'
      - 正则表达式: 'computer/Regular_Expression.md'
      - javascript: 'computer/javascript.md'
      - git : 'computer/git.md'
      - Python: 'computer/python.md'
      - Go: 'computer/go.md'
      - 算法相关:
          - 数据结构与算法: 'computer/algorithm/alg.md'
          - 编程、算法练习:
            - 图论相关: 'computer/algorithm/practice_2/Graph.md'
            - 并查集: 'computer/algorithm/practice_2/UnionFind.md'
          - 第一次练习 : 
            - 九月练习: 'computer/algorithm/sep_practice.md'
            - 十月练习: 'computer/algorithm/oct_practice.md'
            - 十一月练习: 'computer/algorithm/Fri_practice.md'
            - 十二月练习: 'computer/algorithm/Dec_practice.md'

  - 数学物理知识:
      - 数学复习: 'math/math_review.md'
      - 物理知识: 'math/physics.md'
      - 复变函数的微积分: 'math/复变函数的微积分.md'
      - 信息论: 'math/information_theory.md'
      - 概率论和数理统计 : 'math/概率论和数理统计.md'
  
  - 相关知识记录: 
      - 控制知识记录: 'accumulate/控制相关.md'
      - 机器人交叉创新: 'robot/机器人交叉创新.md'
      - 算法练习知识: 'accumulate/算法练习.md'
      - 英语作文: 'accumulate/English.md'
  - 阅读:
      - 合集: 'reading/合集.md'
      - 小米创业思考: 'reading/小米创业思考.md'
      - 心理 : 'reading/心理.md'
      - 银河帝国: 'reading/银河帝国.md'
      - movie : 'reading/movie.md'
      - Economy: 'reading/经济.md'
      - 最懂输的人才能成为赢家: 'reading/最懂输的人才能成为赢家.md'
      
  - 关于: 'record/about.md'



